### ISSUE TITLE
Exception when editing a User

### ISSUE THREAD

**Issue by fabthe** [IdealChain/sese2015#14]
Happened locally at my workstation, although IdealChain could not reproduce.

How to reproduce:
 - Kundenübersicht
 - Beliebigen Kunden auswählen > Bearbeiten
 - Speichern (ohne Änderungen)
 - (check backend output logs)

Backend throws the following exception:
java.lang.NoSuchMethodError: sese2015.g3.goldenlion.customer.dto.CustomerDto.setDiscount(Ljava/lang/Double;)V
	at sese2015.g3.goldenlion.reservation.mapper.CustomerMapperImpl.customerToCustomerDto(CustomerMapperImpl.java:57) ~[classes/:na]
	at sese2015.g3.goldenlion.customer.service.impl.CustomerServiceImpl.updateCustomer(CustomerServiceImpl.java:72) ~[classes/:na]
	at sese2015.g3.goldenlion.customer.resource.CustomerResource.update(CustomerResource.java:52) ~[classes/:na]

**Comment by IdealChain** [comment]
Are these maven warnings related?

    [WARNING] diagnostic: /home/daniel/sese2015/goldenlion-server/src/main/java/sese2015/g3/goldenlion/reservation/mapper/CustomerMapper.java:16: warning: Unmapped target properties: "id, discount, notes".
    CustomerDto reservationCustomerToCustomerDto(ReservationCustomer reservationCustomer);
                ^
    [WARNING] diagnostic: /home/daniel/sese2015/goldenlion-server/src/main/java/sese2015/g3/goldenlion/reservation/mapper/CustomerMapper.java:18: warning: Unmapped target properties: "street, streetExtension, state, postalCode, city, telephone, fax, web, notes".
    CustomerDto customerToCustomerDto(Customer customer);
