### ISSUE TITLE
Customer Reservation: Input data and validation

### ISSUE THREAD

**Issue by oblassers** [IdealChain/sese2015#8]
1. "Bis" date should be on current day + 1, so default values don't result in an "Datumsbereich ungültig" error
2. Number of "Erwachsene" and "Kinder" numeric up down fields should only allow positive values
3. The required fields should be indicated as so, e.g. using a *
4. After input data validation a proper error message should be displayed stating which input was wrong
5. Birthdate input field is not labelled
6. The input field "Postleitzahl" can exceed its limit of 16

**Comment by Mawster** [comment]
Fixxed with  9f7e1ac
